# Generated by Django 4.0.3 on 2022-03-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='link',
            new_name='qr_url',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='is_null',
            field=models.BooleanField(default=True),
        ),
    ]
