# Generated by Django 4.0.3 on 2022-05-26 23:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='address',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
