# Generated by Django 4.0.3 on 2022-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_img',
            field=models.ImageField(null=True, upload_to='qrcode/images'),
        ),
    ]
