# Generated by Django 4.0.3 on 2022-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0002_qrcode_phonenumber_qrcode_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_img',
            field=models.TextField(null=True),
        ),
    ]
