# Generated by Django 4.0.3 on 2022-04-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0002_qrcode_qr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='title',
            field=models.CharField(default='Null', max_length=20),
            preserve_default=False,
        ),
    ]
