# Generated by Django 4.0.3 on 2022-04-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0003_qrcode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='title',
        ),
    ]
