# Generated by Django 4.0.3 on 2022-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0003_alter_qrcode_qr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='address',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
